server:
  port: 8082

spring:
  application:
    name: rating-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingdb
    username: appuser
    password: apppass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.format_sql: true
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
